### ISSUE TITLE
Storage account commands do not honor AZURE_CLI_DISABLE_CONNECTION_VERIFICATION

### ISSUE THREAD

**Issue by rggammon** [Azure/azure-multiapi-storage-python#11]
The Azure CLI has an environment setting called AZURE_CLI_DISABLE_CONNECTION_VERIFICATION, useful if you are eg: using the azure cli in conjunction with fiddler.

It would be great if "az storage" commands also honored this environment variable.

azure.multiapi.storage.v2017_04_17.common.storageclient : Client-Request-ID=11906a36-e061-11e7-b392-3417ebdd5a75 Operation failed: checking if the operation should be retried. Current retry count=1, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='xxx.file.core.windows.net', port=443): Max retries exceeded with url: ... (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)).

**Comment by troydai** [comment]
@rggammon if it is an issue related to the Azure CLI, please file it in the azure-cli repository. This repository serves only as the multiapi SDK. Thanks.
